### ISSUE TITLE
Get para Stats

### ISSUE THREAD

**Issue by Nicu1309** [ProjectMOA/noTeRayesCo#1]
Cómo vas a acceder a la cuenta de visitas? Puedo hacer un endpoint a parte para que nada más llegarte hagas post aunque será más ineficiente, de momento cada vez que pides el index se hace la cuenta. Tendrás que hacer un get para recoger las estadísticas al llegarte el index. Está así bien?

**Comment by nebur395** [comment]
Acabo de añadir un get a un endpoint llamado **getVisits** el cual únicamente recoge un númer, lo puedes ver en la línea 73 del [index](https://github.com/nebur395/noTeRayesCo/blob/master/public/index.html), en  principio debería funcionar con tal de quitarle el número que tiene de "mockup" y descomentar el response.data. Yo creo que así suficiente, no?
