### ISSUE TITLE
Create test branch

### ISSUE THREAD

**Issue by Nicu1309** [ProjectMOA/noTeRayesCo#12]
So as changes don't affect to heroku published version. Need approval.

**Comment by nebur395** [comment]
I'm agree with you. Another option is disable the automatic branch release of heroku, but I think that test branch will be a better long-term solution.

**Comment by Nicu1309** [comment]
Created devel branch and reverted button commit on master. This change can be found on new devel branch. Can I close this issue now? Please pull your repos to have the new structure.

**Comment by nebur395** [comment]
Thanks for the quickness.  Good Job man saucepan. :octocat:
